[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "number-guesser"
version = "0.1.0"
requires-python = ">=3.8"

[tool. setuptools.packages.find]
where = ["src"]